# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aprobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripccion', models.TextField(null=True)),
                ('nocaer', models.TextField(null=True)),
                ('defininicion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ataque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion', models.TextField(null=True)),
                ('comofunciona', models.TextField(null=True)),
                ('comoevitarlo', models.TextField(null=True)),
                ('tipos', models.TextField(null=True)),
                ('video', models.CharField(max_length=200, null=True)),
                ('recomendaciones', models.TextField(null=True)),
                ('pasosaseguir', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ataque',
            name='tipoataque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsoft.tipo'),
        ),
        migrations.AddField(
            model_name='aprobo',
            name='tipoataque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsoft.tipo'),
        ),
    ]
